name: Adventures
author: fullwall
version: 1.0
main: net.citizensnpcs.adventures.Adventures
depend: [Citizens]
softdepend: [Denizen]
commands:
    adventures:
        description: Adventures admin commands
    dialog:
        description: Adventures dialog commands
    race:
        description: Adventures race commands
    tribe:
        description: Adventures tribe commands